---

- name: Create and configure ansible-gnome-terminal
  hosts: client

  # TODO local testing only
  # debugger: on_failed

  roles:
    - role: ansible-gnome-terminal
      tasks_from: main
      gnome_terminal_state: present
      custom_profile: true

...
